name: Update Discord Roles

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-roles:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.13.2
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.2'  # Ensure Python 3.13.2 is installed

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libffi-dev libnacl-dev python3-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r discord_bot/config/discord_bot_requirements.txt

      - name: Create empty JSON files if they don't exist
        run: |
          [ -f contributions.json ] || echo '{}' > contributions.json
          [ -f repo_metrics.json ] || echo '{"stars_count": 0, "forks_count": 0}' > repo_metrics.json
          [ -f contributions_progress.json ] || echo '{"all_contributions": {}, "processed_repos": [], "timestamp": ""}' > contributions_progress.json
          echo "Created or verified existence of necessary JSON files"

      - name: Set up Google Credentials
        run: echo "${{ secrets.GOOGLE_CREDENTIALS_JSON }}" | base64 --decode > discord_bot/config/credentials.json

      - name: Fetch GitHub contributions 
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: | 
          python discord_bot/src/utils/fetch_contributors.py   

      - name: Update Firestore
        env:
          GOOGLE_APPLICATION_CREDENTIALS: discord_bot/config/credentials.json
        run: |
          python discord_bot/src/utils/firestore.py

      - name: Update Discord roles
        env: 
            DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        run: |  
          python discord_bot/src/utils/update_discord_roles.py
